In [7]:
import numpy as np

In [ ]:
1. Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.

In [43]:
a = np.ones((10,10))
a[1:9,1:9] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
2. Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.

In [30]:
a = np.ones((8,8))
a[0:7:2,0:8:2] = 0
a[1:8:2,1:7:2]=0
print(a)

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 1.]])

In [ ]:
3. Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули

In [35]:
a = np.zeros((5,5))
a[1:,0:-1] = np.diag((1,2,3,4))
print(a)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [ ]:
4. Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее вдоль каждой строки было равно нулю.

In [54]:
a = np.random.random((5, 5))
b = np.mean(a, axis=1).reshape((-1,1))
print(a-b, "\n")
print(np.mean(a-b, axis=1))

[[-0.04231496  0.33370463 -0.06922691  0.2208451  -0.44300786]
 [ 0.0556916   0.28484412 -0.19108719 -0.23637978  0.08693124]
 [ 0.20781871 -0.03328457 -0.09178492 -0.03266999 -0.05007923]
 [ 0.05743245  0.10985803  0.26642458 -0.40508054 -0.02863453]
 [-0.3487716  -0.19836876 -0.25849082  0.46546899  0.34016219]] 

[ 0.00000000e+00 -4.44089210e-17 -1.11022302e-17  0.00000000e+00
  0.00000000e+00]


In [ ]:
5. Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.

In [74]:
a = np.random.random((10, 3))
print(a, "\n")
b = np.abs(a-0.5)
c = np.argmin(b,axis=1)
print(a[np.arange(10),c].reshape((-1,1)))

[[0.96471455 0.7823367  0.96624707]
 [0.42684839 0.44188437 0.12293563]
 [0.7045744  0.26399241 0.96380961]
 [0.65180963 0.00544623 0.23848519]
 [0.00298909 0.89216388 0.72068015]
 [0.63011643 0.12375653 0.83162008]
 [0.3515694  0.99063271 0.07939955]
 [0.86063614 0.84789462 0.61070323]
 [0.03065668 0.82682424 0.99229525]
 [0.85242394 0.14989074 0.9077905 ]] 

[[0.7823367 ]
 [0.44188437]
 [0.7045744 ]
 [0.65180963]
 [0.72068015]
 [0.63011643]
 [0.3515694 ]
 [0.61070323]
 [0.82682424]
 [0.14989074]]


In [ ]:
6. Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

In [76]:
a = np.random.random((6,6))
print(a)
b = np.sum(a, axis = 1)/a.max(axis=0)
print(b)

[[0.78941899 0.18775486 0.76036777 0.15825439 0.0653694  0.55197119]
 [0.93956755 0.25138857 0.11376729 0.76456676 0.44826972 0.25269334]
 [0.19793532 0.09192545 0.60321948 0.5581068  0.52887439 0.08579219]
 [0.53206115 0.91464838 0.01845043 0.61840663 0.59622267 0.02311712]
 [0.7670303  0.31985144 0.9824651  0.20455559 0.43659941 0.11550564]
 [0.72707942 0.56031659 0.17859576 0.75589895 0.85739031 0.10537491]]
[2.67478012 3.02876305 2.10272471 3.53521304 3.29605716 5.76960535]


In [ ]:
7. На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [86]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
a = x[1:][(x==0)[:-1]].max()
print(a)


5


In [ ]:
8. Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [104]:
x = np.ones(10, dtype = 'int')
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
x += (i.reshape(len(i), 1) == np.arange(len(x))).sum(axis=0)
print(x)

[2 2 2 2 1 4 1 1 2 1]


In [ ]:
9. Задайте два массива
a = np.array([[1, 4.9, 2.4], [7.1, 7, 9.8], [2, 4.6, 1.2]]) и
b = np.array([3, 5, 10, 0]). Создайте массив, в котором каждый элемент первого массива заменен на ближайший к нему элемент второго массива.

In [150]:
a = np.array([[1, 4.9, 2.4], [7.1, 7, 9.8], [2, 4.6, 1.2]])
b = np.array([3, 5, 10, 0])
c = b[np.argmin(abs(a.reshape(3,3,1) - b.reshape(1,1,4)), axis = 2)]
print(c)

[[ 0  5  3]
 [ 5  5 10]
 [ 3  5  0]]


In [ ]:
10. Найдите скользящие средние с окном размера 3 по массиву a = np.array([1, 4.9, 2.4, 7.1, 7, 9.8, 2, -5, 4.6, 1.2]).

In [149]:
a = np.array([1, 4.9, 2.4, 7.1, 7, 9.8, 2, -5, 4.6, 1.2])
window = 3
moving_avg = np.convolve(a, np.ones(window)/window, mode='valid')
print(moving_avg)

[2.76666667 4.8        5.5        7.96666667 6.26666667 2.26666667
 0.53333333 0.26666667]
